# fly.toml app configuration file generated for www-babalada-com on 2023-06-17T20:15:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "www-babalada-com"
primary_region = "den"

[http_service]
	internal_port = 8080
	force_https = true
	auto_stop_machines = true
	auto_start_machines = true
	min_machines_running = 1

[[services]]
	internal_port = 5000
	protocol = "tcp"
	[[services.ports]]
		handlers = ['tls', 'http']
		port = 5000