"""Made changes to user

Revision ID: 170584513bc8
Revises: f4d801513fba
Create Date: 2023-07-27 18:00:26.183714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170584513bc8'
down_revision = 'f4d801513fba'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
