"""made changes

Revision ID: 383410547834
Revises: ad477dbc3714
Create Date: 2023-07-25 00:47:57.673789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383410547834'
down_revision = 'ad477dbc3714'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
