"""Made changes to user

Revision ID: 45401fe8786c
Revises: 170584513bc8
Create Date: 2023-07-27 18:10:03.309353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45401fe8786c'
down_revision = '170584513bc8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photoUrl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photoUrl')
    # ### end Alembic commands ###
