"""added description to Portfolio table

Revision ID: 4b3520d12f92
Revises: 23fb01c0d076
Create Date: 2023-07-25 15:07:09.751582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3520d12f92'
down_revision = '23fb01c0d076'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
