"""added description to Portfolio table

Revision ID: 535be6be5d4d
Revises: 4b3520d12f92
Create Date: 2023-07-25 15:10:03.531472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535be6be5d4d'
down_revision = '4b3520d12f92'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
