"""added default to balance

Revision ID: 7d4bfe07150f
Revises: c73f7874ea1e
Create Date: 2023-06-23 17:30:50.731812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4bfe07150f'
down_revision = 'c73f7874ea1e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
