"""made changes

Revision ID: 94b2e369fd68
Revises: 383410547834
Create Date: 2023-07-25 00:55:17.968920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b2e369fd68'
down_revision = '383410547834'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('portfolioId', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('portfolioName', sa.String(length=100), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('portfolioId')
    )
    op.drop_column('investment_transacted', 'shares_purchased')
    op.drop_column('user', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('investment_transacted', sa.Column('shares_purchased', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('portfolio')
    # ### end Alembic commands ###
