"""made changes

Revision ID: ad477dbc3714
Revises: 7d4bfe07150f
Create Date: 2023-07-25 00:45:10.555715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad477dbc3714'
down_revision = '7d4bfe07150f'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transacted', sa.Column('shares_purchased', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transacted', 'shares_purchased')
    # ### end Alembic commands ###
